# A Docker Compose application with moqui, mysql, and virtual hosting through
#   nginx-proxy supporting multiple moqui instances on different hosts.

# Test locally by adding the virtual host to /etc/hosts or with something like:
#   curl -H "Host: moqui.local" localhost/Login

version: "2"
services:
  nginx-proxy:
    # For documentation on SSL and other settings see:
    # https://github.com/jwilder/nginx-proxy
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  moqui-server:
    image: moqui
    command: --conf=conf/MySQLConf.xml
    restart: always
    links:
     - mysql-moqui
    volumes:
     - ./runtime/conf:/opt/moqui/runtime/conf
     - ./runtime/lib:/opt/moqui/runtime/lib
     - ./runtime/classes:/opt/moqui/runtime/classes
     - ./runtime/log:/opt/moqui/runtime/log
     - ./runtime/txlog:/opt/moqui/runtime/txlog
     # this one isn't needed: - ./runtime/db:/opt/moqui/runtime/db
     - ./runtime/elasticsearch:/opt/moqui/runtime/elasticsearch
    environment:
     - ds_transactional_host=mysql-moqui
     - ds_transactional_port=3306
     - ds_transactional_database=MoquiDEFAULT
     - ds_transactional_user=moqui
     - ds_transactional_password=moqui
     # CHANGE ME
     - VIRTUAL_HOST=moqui.local
     - VIRTUAL_PORT=8080

  mysql-moqui:
    image: mysql:5.7
    restart: always
    # uncomment this to expose the port for use outside other services
    # ports:
    #  - 3306:3306
    # edit these as needed to map configuration and data storage
    volumes:
     - ./db/mysql/data:/var/lib/mysql
     # - /my/mysql/conf.d:/etc/mysql/conf.d
    environment:
     - MYSQL_ROOT_PASSWORD=moquitest
     - MYSQL_DATABASE=MoquiDEFAULT
     - MYSQL_USER=moqui
     - MYSQL_PASSWORD=moqui
